apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
  labels:
    app: web
spec:
  nodeSelector:
    az: ap-northeast-2a
  containers:
  - image: nginx:1.14
    name: test-container
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-volume
  volumes:
  - name: test-volume
    # 이 AWS EBS 볼륨은 이미 존재해야 한다.
    awsElasticBlockStore:
      volumeID: "vol-07ab4a74f151ea1d1"
      fsType: ext4
