apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true

      volumes:
      - name: html
#        hostPath:
#          path: /webdata
        awsElasticBlockStore:
          volumeID: vol-06eee1538b04875e6
          fsType: xfs
