apiVersion: v1
kind: Pod
metadata:
  name: redis-ssd
spec:
  containers:
  - name: redis
    image: redis
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - {key: KEY, operator: In, values: ["VALUE"]}
